services:
  bot:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    #ports:
    #  - 8008:8000
    expose:
      - 8000

    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.bot.entrypoints=https"
      - "traefik.http.routers.bot.rule=Host(`old.kik-soft.ru`)"
      - "traefik.http.routers.bot.tls=true"
      - "traefik.http.routers.bot.tls.certresolver=letsEncrypt"
      - "traefik.http.services.bot-service.loadbalancer.server.port=80"